"""抖音访客 Cookie 自动获取（基于 Playwright + Chromium）。"""
from __future__ import annotations

import os
from pathlib import Path

from playwright.sync_api import sync_playwright


def _default_cookie_path() -> Path:
    root = Path(__file__).resolve().parents[2]
    return root / "models" / "douyin_cookies.txt"


def save_cookies_netscape(cookies: list[dict], output_path: str) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by VideoBridge for douyin.com",
    ]
    for c in cookies:
        name = c.get("name") or ""
        value = c.get("value") or ""
        if not name:
            continue
        domain = c.get("domain") or ""
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        expires = int(c.get("expires", 0) or 0)
        if expires < 0:  # playwright 用 -1 表示会话 Cookie，Netscape 格式应为 0
            expires = 0
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return output_path


def fetch_douyin_cookies(output_path: str | None = None) -> str:
    """静默打开抖音首页，等待生成访客 Cookie 后保存为 cookies.txt。"""
    output_path = output_path or str(_default_cookie_path())
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            args=["--disable-blink-features=AutomationControlled"],
        )
        try:
            ctx = browser.new_context(
                user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
            )
            page = ctx.new_page()
            page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=30000)
            page.wait_for_timeout(8000)
            cookies = ctx.cookies()
            if len(cookies) < 5:
                page.wait_for_timeout(5000)
                cookies = ctx.cookies()
            save_cookies_netscape(cookies, output_path)
        finally:
            browser.close()

    if not os.path.isfile(output_path) or os.path.getsize(output_path) == 0:
        raise RuntimeError("自动获取抖音 Cookie 失败")
    return output_path
